name: Build Android and iOS
on:
  push:
    branches:
      - master
jobs:
  # this is job key
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      # brings source code to virtual machine
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test